# Generated by Django 3.1.3 on 2020-11-29 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwardsapp', '0002_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contact_information',
            field=models.TextField(default='+254'),
        ),
        migrations.AddField(
            model_name='projects',
            name='title',
            field=models.CharField(default='My Project', max_length=50),
        ),
    ]
